// <auto-generated />
namespace ControlePatrimonio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tempo_Garantia_not_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tempo_Garantia_not_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011816112_Tempo_Garantia_not_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
