// <auto-generated />
namespace ControlePatrimonio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataExpiracao_vida_util_produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataExpiracao_vida_util_produto));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061048358_DataExpiracao_vida_util_produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
